version: '3.4'

services:
  jupyter:
    image: jupyter/scipy-notebook
    restart: 'no'
    ports:
      - "8888:8888"
    volumes:
      - ".:/home/jovyan"

    command:
      "jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password=''"

  openrefine:
    image: ghcr.io/aot29/docker-openrefine:master
    restart: 'no'
    ports:
      - "3333:3333"
    volumes:
      - ".:/data"
    environment:
      - REFINE_INTERFACE=0.0.0.0
      - REFINE_PORT=3333
      - REFINE_MEMORY=1024M
      - REFINE_DATA_DIR=/data

networks:
  default:
    external: true
    name: portal-compose_default

